---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{CF_REPO_NAME}}
  labels:
    app: {{CF_REPO_NAME}}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      name: {{CF_REPO_NAME}}
      labels:
        app: {{CF_REPO_NAME}}
        tier: web
    spec:
      imagePullSecrets:
        - name: dockerhub-instapartners
      containers:
        - name: {{CF_REPO_NAME}}
          image: {{BUILD_IMAGE}}
          imagePullPolicy: Always
          env:
            - name: MIAOW
              value: {{MIAOW}}
            - name: PORT
              value: "{{PORT}}"
            - name: LOGGING_LEVEL
              value: {{LOGGING_LEVEL}}
          envFrom:
          - configMapRef:
              name: {{CF_REPO_NAME}}-environment-variables
          ports:
          - name: web
            containerPort: 80
      # readinessProbe:
        # tcpSocket:
          # port: 8080
        # initialDelaySeconds: 5
        # periodSeconds: 10
      # livenessProbe:
        # tcpSocket:
          # port: 8080
        # initialDelaySeconds: 15
        # periodSeconds: 20

