# https://github.com/kubernetes/ingress-gce/blob/master/docs/annotations.md
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: {{CF_REPO_NAME}}-ingress
    annotations:
      kubernetes.io/ingress.class: {{INGRESS_CLASS}}
  spec:
    rules:
    - host: {{HOST}}
      http:
        paths:
        - backend:
            serviceName: {{CF_REPO_NAME}}
            servicePort: 80
          path: /
